org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=false

# Mod Properties
mod_version = 0.1.0
maven_group = github.jorbon
project_id = bot_mode

# Ralli driven values
minecraft_compatible_range=[">=1.21.10 <1.21.11"]
enforce_range=false
minecraft_version=1.21.10
yarn_mappings=1.21.10+build.3
java_version=21
loom_version=1.17-SNAPSHOT
loader_version=0.19.3

# Dependencies
fabric-api=0.138.4+1.21.10
